#!/usr/bin/env python3
"""Build the board fixture `pcb-lint` is developed against.

The point of the fixture is that it contains, in real KiCad geometry, every
defect `hw-verification/references/pcb-layout.md` was written about — a
thermal-via array punching through onto opposite-side copper, a net class
whose track width no pad on its nets can accept, a clearance that violates
itself inside a footprint, a decoupling capacitor a dozen millimetres from the
pin it serves, and silkscreen across a pad. A linter validated only against
clean boards proves nothing.

It is **generated by `pcbnew`**, never hand-written. `pcb-layout.md` §0 is
explicit that KiCad's own Python API is the escape hatch when the IPC socket is
not there, and that it "is not text manipulation of a `.kicad_pcb`, which is
never acceptable". Writing a board by hand would make this the only
hand-written KiCad file in the repository, and a linter checked against a file
its own author typed is a linter that agrees with itself.

    ./build-pcb-fixture.py            # writes hw/lint-fixture.kicad_pcb + .kicad_pro

Needs `pcbnew` from a KiCad 9/10 install. Without it the committed fixture
stands and this is skipped, the same way `build-fixture.sh` treats
`kicad-cli`.
"""
from __future__ import annotations

import json
import os
import subprocess
import sys

try:
    import pcbnew
except ImportError:
    # KiCad's bindings live in whichever interpreter the distribution built
    # them for, which is usually the system python3 rather than the hardware
    # toolchain's. Re-exec there once rather than reporting "no pcbnew" on a
    # machine that has it.
    import shutil
    alt = shutil.which("python3")
    if alt and not os.environ.get("MH_PCB_FIXTURE_REEXEC"):
        os.environ["MH_PCB_FIXTURE_REEXEC"] = "1"
        r = subprocess.run([alt, os.path.abspath(__file__)] + sys.argv[1:])
        sys.exit(r.returncode)
    print("no pcbnew — keeping the committed fixture")
    sys.exit(0)

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "hw", "lint-fixture.kicad_pcb")
PRO = os.path.join(HERE, "hw", "lint-fixture.kicad_pro")
FPDIR = os.environ.get("KICAD_FOOTPRINT_DIR", "/usr/share/kicad/footprints")

W, H = 40.0, 26.0


def mm(v):
    return pcbnew.FromMM(v)


def vec(x, y):
    return pcbnew.VECTOR2I(mm(x), mm(y))


def load(lib, name):
    fp = pcbnew.FootprintLoad(os.path.join(FPDIR, lib + ".pretty"), name)
    if fp is None:
        raise SystemExit(f"footprint not found: {lib}:{name}")
    return fp


def place(board, lib, name, ref, value, x, y, rot=0.0, back=False):
    fp = load(lib, name)
    fp.SetReference(ref)
    fp.SetValue(value)
    fp.SetPosition(vec(x, y))
    if rot:
        fp.SetOrientationDegrees(rot)
    board.Add(fp)
    if back:
        fp.Flip(vec(x, y), False)
    return fp


def net(board, name):
    ni = board.FindNet(name)
    if ni is None:
        ni = pcbnew.NETINFO_ITEM(board, name)
        board.Add(ni)
    return ni


def assign(fp, mapping, board):
    """mapping: {pad number: net name}. Anything unnamed stays on net 0."""
    for pad in fp.Pads():
        want = mapping.get(pad.GetNumber())
        if want:
            pad.SetNet(net(board, want))


def outline(board):
    edge = board.GetLayerID("Edge.Cuts")
    corners = [(0, 0), (W, 0), (W, H), (0, H), (0, 0)]
    for (x1, y1), (x2, y2) in zip(corners, corners[1:]):
        seg = pcbnew.PCB_SHAPE(board)
        seg.SetShape(pcbnew.SHAPE_T_SEGMENT)
        seg.SetStart(vec(x1, y1))
        seg.SetEnd(vec(x2, y2))
        seg.SetLayer(edge)
        seg.SetWidth(mm(0.1))
        board.Add(seg)


def main() -> int:
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    board = pcbnew.NewBoard(OUT)
    outline(board)

    for n in ("GND", "VDD", "SENSE", "SW_NODE"):
        net(board, n)

    # --- PCB-THERMVIA -----------------------------------------------------
    # An exposed-pad part whose _ThermalVias variant carries a via array under
    # the pad, placed directly opposite a part on the other side whose pads sit
    # on a different net. This is the one that reaches fabrication.
    u1 = place(board, "Package_SO",
               "MSOP-8-1EP_3x3mm_P0.65mm_EP1.5x1.8mm_ThermalVias",
               "U1", "TPS62840", 12.0, 13.0)
    assign(u1, {"1": "SW_NODE", "2": "GND", "5": "VDD", "8": "VDD",
                "9": "GND"}, board)

    # The part that gets shorted: a bypass capacitor tucked on the back under
    # the IC, which is exactly where a placement pass puts one, with its pads
    # landing on the via row.
    c3 = place(board, "Capacitor_SMD", "C_0402_1005Metric",
               "C3", "1uF", 12.0, 12.35, back=True)
    assign(c3, {"1": "SENSE", "2": "SW_NODE"}, board)

    u2 = place(board, "Package_SO", "SOIC-8_3.9x4.9mm_P1.27mm",
               "U2", "OPA377", 27.0, 8.0, back=True)
    assign(u2, {"1": "SENSE", "4": "GND", "7": "SENSE", "8": "VDD"}, board)

    # --- PCB-DECAP --------------------------------------------------------
    # One capacitor where it belongs and one where it does not, so the ranking
    # has something to rank and the check has a control.
    c1 = place(board, "Capacitor_SMD", "C_0402_1005Metric",
               "C1", "100nF", 12.0, 10.6)
    assign(c1, {"1": "VDD", "2": "GND"}, board)

    c2 = place(board, "Capacitor_SMD", "C_0402_1005Metric",
               "C2", "100nF", 30.0, 21.0)
    assign(c2, {"1": "VDD", "2": "GND"}, board)

    # --- PCB-TRACKW / PCB-CLEAR ------------------------------------------
    # A 0402 pad is 0.5 mm wide and the MSOP's signal pads are 0.4 mm at
    # 0.65 mm pitch, i.e. a 0.25 mm gap. The Power class below asks for a
    # 1.20 mm track and 0.30 mm clearance against both.
    j1 = place(board, "Connector_JST", "JST_PH_S2B-PH-K_1x02_P2.00mm_Horizontal",
               "J1", "VIN", 4.0, 22.0)
    assign(j1, {"1": "VDD", "2": "GND"}, board)

    # --- PCB-SILK ---------------------------------------------------------
    # A reference designator dragged onto its own pads, which is what an
    # autoplacer does when the courtyard is tight.
    ref = u1.Reference()
    ref.SetPosition(vec(12.0, 13.0))
    ref.SetTextSize(pcbnew.VECTOR2I(mm(0.5), mm(0.5)))   # under min_text_height

    if not pcbnew.SaveBoard(OUT, board):
        print("SaveBoard failed", file=sys.stderr)
        return 1

    # The project file is JSON, not an S-expression KiCad file, so writing it
    # here is not the thing the never-hand-edit rule is about. It is also the
    # only place net classes live — they are not in the .kicad_pcb at all,
    # which is the single most important fact about writing a PCB linter.
    pro = {
        "board": {
            "design_settings": {
                "rules": {
                    "min_clearance": 0.2,
                    "min_track_width": 0.2,
                    "min_text_height": 0.8,
                    "min_text_thickness": 0.15,
                    "min_silk_clearance": 0.15,
                }
            }
        },
        "meta": {"filename": os.path.basename(PRO), "version": 3},
        "net_settings": {
            "classes": [
                {"name": "Default", "clearance": 0.2, "track_width": 0.25,
                 "via_diameter": 0.6, "via_drill": 0.3, "priority": 2147483647},
                {"name": "Power", "clearance": 0.3, "track_width": 1.2,
                 "via_diameter": 0.8, "via_drill": 0.4, "priority": 0},
            ],
            "netclass_patterns": [
                {"netclass": "Power", "pattern": "VDD"},
                {"netclass": "Power", "pattern": "GND"},
            ],
            "netclass_assignments": {},
        },
        "pcbnew": {"last_paths": {}},
    }
    with open(PRO, "w") as fh:
        json.dump(pro, fh, indent=2)

    print(f"wrote {os.path.relpath(OUT, HERE)} "
          f"({os.path.getsize(OUT):,} bytes) and its .kicad_pro")
    return 0


if __name__ == "__main__":
    sys.exit(main())
