"""Rebuild this assembly in FreeCAD 1.0 with real, editable joints.

Generated by MakeHardware `cad-export`. Do not edit — edit the build123d
module it came from and re-export, or the next export overwrites your work.

    FreeCAD -> Macro -> Macros... -> select this file -> Execute
    (or: freecadcmd enclosure-freecad.py)

STEP carries the assembly tree, the part names, the colours and the
placement, but it does not carry mates: AP242 edition 2 defines kinematics,
OCCT does not write them and FreeCAD does not read them. This macro closes
that gap by importing the STEP and then creating the joints from the JSON
beside it, so what you open is an assembly you can actually drag.
"""
import json
import os

import FreeCAD as App
import Import

HERE = os.path.dirname(os.path.abspath(__file__))
STEP = os.path.join(HERE, 'enclosure.step')
JOINTS = os.path.join(HERE, 'enclosure-joints.json')
OUT = os.path.join(HERE, 'enclosure.FCStd')

doc = App.newDocument('enclosure')
Import.insert(STEP, doc.Name)

try:
    import UtilsAssembly  # noqa: F401  — present only in FreeCAD 1.0+
except ImportError:
    App.Console.PrintWarning(
        "This FreeCAD has no Assembly workbench (1.0 or newer is needed).\n"
        "The geometry imported, but the joints below were not created.\n")
    doc.recompute()
    doc.saveAs(OUT)
    raise SystemExit(0)

asm = doc.addObject("Assembly::AssemblyObject", "Assembly")
for obj in list(doc.Objects):
    if obj is asm:
        continue
    if obj.TypeId.startswith("Part::") and obj.getParentGeoFeatureGroup() is None:
        asm.addObject(obj)

by_label = {}
for obj in doc.Objects:
    by_label.setdefault(obj.Label, obj)

created, skipped = 0, []
for j in json.load(open(JOINTS)):
    part = by_label.get(j["part"])
    other = by_label.get((j.get("connected_to") or {}).get("part", ""))
    if part is None:
        skipped.append(f"{j['part']}.{j['name']} (no such part in the STEP)")
        continue
    jo = doc.addObject("Assembly::Joint" + j["freecad_type"],
                       f"{j['part']}_{j['name']}")
    asm.addObject(jo)
    pos = j.get("position_mm", [0, 0, 0])
    rot = j.get("rotation_deg", [0, 0, 0])
    placement = App.Placement(App.Vector(*pos),
                              App.Rotation(rot[2], rot[1], rot[0]))
    try:
        jo.Reference1 = [part, [""]]
        jo.Placement1 = placement
        if other is not None:
            jo.Reference2 = [other, [""]]
            jo.Placement2 = placement
    except Exception as exc:                 # FreeCAD property names move
        skipped.append(f"{j['part']}.{j['name']} ({exc})")
        continue
    lim = j.get("angle_limits_deg")
    if lim and hasattr(jo, "EnableLimitAngle"):
        jo.EnableLimitAngle = True
        jo.LimitAngleMin, jo.LimitAngleMax = lim
    lim = j.get("linear_limits_mm")
    if lim and hasattr(jo, "EnableLimitLength"):
        jo.EnableLimitLength = True
        jo.LimitLengthMin, jo.LimitLengthMax = lim
    created += 1

doc.recompute()
doc.saveAs(OUT)
App.Console.PrintMessage(f"created {created} joint(s); saved {OUT}\n")
for s in skipped:
    App.Console.PrintWarning(f"skipped {s}\n")
